version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo start prebuild and end it    
  build:
    commands:
      - echo Running buuild
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync . s3://doctor-website-build/
      - echo Build completed successfully

artifacts:
  files:
    - "**/*" # Include all files in the artifact
  base-directory: .  # Specify where artifacts are stored
